### ISSUE TITLE
[Suggestion] Permissions

### ISSUE THREAD

**Issue by BroCrows** [AlecksWasHere/ChatFX#2]
I really want only certain players to be able to use certain types of colors.
Could you add a permission for cfx and all the colors.

**Comment by BroCrows** [comment]
After looking at the code, there is a command permission(might want to add it to plugin.yml)
But anyways add the perms for each of the colors

**Comment by alacksch** [comment]
I will be looking into separating permissions. :)

**Comment by alacksch** [comment]
Added. Next official update will probably have it. Thanks for the suggestion!

**Comment by BroCrows** [comment]
If you mean the latest update it didn’t have what I suggested...
I was suggesting a permission for each color...
Ex.
chatfx.color.rainbow
or
chatfx.rainbow

**Comment by alacksch** [comment]
I know :) the source code I have on Github currently supports that, the
next Poggit update I meant.

**Comment by alacksch** [comment]
I have submitted the latest build to Poggit, expect it on there soon, unless rejected which will eventually be fixed. What you asked for is currently implemented!
![one](https://user-images.githubusercontent.com/52435658/120629594-07720f80-c477-11eb-999b-485a6b772981.png)
![two](https://user-images.githubusercontent.com/52435658/120629598-08a33c80-c477-11eb-84d6-37eab1fca211.png)
