### ISSUE TITLE
[Suggestion] Config

### ISSUE THREAD

**Issue by BroCrows** [AlecksWasHere/ChatFX#5]
Could you add a config to enable/disable colors and to edit the messages?

**Comment by alacksch** [comment]
I think it'd be easier to entirely remove the permission (the color), from specific players if you don't want them to use it, that's if I am who's thinking. Regarding customizable text messages, of course! Tomorrow for sure as it's late right now.

**Comment by alacksch** [comment]
Unless you have a big player base, actually, I might consider looking into the configs function you have mentioned. Thanks for the idea!
